# Generated by Django 4.1.7 on 2023-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_year_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField()),
                ('question_answer', models.TextField()),
                ('exam_name', models.ManyToManyField(to='api.exam')),
            ],
        ),
    ]
