# Generated by Django 4.1.7 on 2023-03-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_book_name_book_book_publication_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.year'),
        ),
    ]
