# Generated by Django 4.1.7 on 2023-03-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.ForeignKey(default='First Year', on_delete=django.db.models.deletion.CASCADE, to='api.year'),
        ),
    ]
